### ISSUE TITLE
[Extension] Version for Firefox

### ISSUE THREAD

**Issue by NikkelM** [NikkelM/Random-YouTube-Video#134] opened 2023-04-13 07:53 UTC
What would we need to do to port this to Firefox?

**Comment by NikkelM** [comment] 2023-04-13 08:21
It seems that some code actions would need to be re-written (e.g. using `browser` instead of `chrome` namespaces, or using promises instead of callbacks).

**Comment by TheAxlelotl** [comment] 2023-04-15 13:12
You don't need to use `browser` instead of `chrome`. Firefox supports the `chrome` namespace to make porting Chrome extension to Firefox easier.

I've been trying to port this extension to Firefox for the past 2 days (I'm the one who suggested porting the extension to Firefox in the review section of chrome web store).

From what I've found out, it would've been really easy to port the extension to Firefox, but the problem is that Firefox doesn't support service workers in Manifest V3 yet. It wants you to use background scripts.

Change this:
```
"background": {
     "service_worker": "js/background.js"
 }
```

To this:
```
"background": {
  "scripts": ["js/background.js"],
 }

```
And you'll be able to install the extension to Firefox, but the extension won't work properly. And it'll give you these warning details:

Reading manifest: Warning processing key: An unexpected property was found in the WebExtension manifest.

**Comment by NikkelM** [comment] 2023-04-15 14:00
(@TheAxlelotl: I got your comment via mail, but can't see it here, but I'll answer anyways ;))
Thanks for the info regarding browser/chrome namespaces, I had only looked at some of the Firefox documentation, but the article may have been outdated. I'll definitely take another look at this then, as it seems to be easier than I thought.

Regarding the manifest error you mentioned: This actually refers to the `key` key (unlucky coincidence). This is used to fix the extension ID for the chrome store, but can safely be removed. 
Loading the extension in Firefox is possible after doing so, however, there are still some errors when running it - e.g. the popup can't be loaded correctly, and if you inspect the background worker, you will see that the `self.importScripts()` function (which is used to import the Firebase code) doesn't work in Firefox/doesn't work as easily as in chromium-based browsers.
So there are still some errors, which I might take a look at. If as you said you are already working on a port, feel free to fork the repository and try things out, perhaps the first batch of info I was able to give you just now will already help a bit.

**Comment by TheAxlelotl** [comment] 2023-04-15 14:55
@NikkelM Thank you so much for answering! I actually deleted my comment because I wanted to try a bit more and see if I can give more information about the problem before commenting again. Maybe even finish porting the extension myself if possible.

I really loved the extension and was surprised that it isn't as popular as it should be, and I want it to be in Firefox and help it gain more traction.

I'll try working on the port again using the information that you gave me, and I'll give you an update soon.

**Comment by NikkelM** [comment] 2023-04-15 14:59
No worries, any info is always better than no info at all. Feel free to get back to me here if there's anything else you're not sure about and I'll see how I can help.
And thanks for the kind words, I'm really happy that the project is useful to others as well :)

**Comment by TheAxlelotl** [comment] 2023-04-18 09:38
@NikkelM Alright. Time for a report.

Regarding the `self.importScripts()` error, it is happening because Firefox wants you to use a web worker in order to access the `importScripts()` method, so you need to move the Firebase section of your code into a separate file, for example, `worker.js`, and then instantiate a web worker object in your `background.js` like this:

`const worker = new Worker('./worker.js');`

This will allow `background.js` to communicate with `worker.js` using messages. For example

`background.js`:

```
/ ---------- Web Worker ----------

const worker = new Worker('./worker.js');

// ---------- Message handler ----------

chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
	switch (request.command) {
		// Tries to get the playlist from Firebase
		case "getPlaylistFromDB":
			// replace readDataOnce('uploadsPlaylists/' + request.data).then(sendResponse);
			worker.addEventListener('message', (event) => {
				if (event.data.command === 'readDataOnce') {
					sendResponse(event.data.message);
				}
			})

			worker.postMessage({
				command: 'readDataOnce',
				message: 'uploadsPlaylists/' + request.data
			})
			break;
		// Updates (without overwriting videos) the playlist in Firebase 
		case "updatePlaylistInfoInDB":
			// replace updatePlaylistInfoInDB(request.data.key, request.data.val, false).then(sendResponse);
			worker.addEventListener('message', (event) => {
				if (event.data.command === 'updatePlaylistInfoInDB') {
					sendResponse(event.data.message);
				}
			})

			worker.postMessage({
				command: 'updatePlaylistInfoInDB',
				message: {
					playlistId: request.data.key,
					playlistInfo: request.data.val,
					overwriteVideos: false
				}
			})
			break;
		// Updates (with overwriting videos, as some were deleted and we do not grant 'delete' permissions) the playlist in Firebase
		case "overwritePlaylistInfoInDB":
			// replace updatePlaylistInfoInDB(request.data.key, request.data.val, true).then(sendResponse);
			worker.addEventListener('message', (event) => {
				if (event.data.command === 'overwritePlaylistInfoInDB') {
					sendResponse(event.data.message);
				}
			})

			worker.postMessage({
				command: 'overwritePlaylistInfoInDB',
				message: {
					playlistId: request.data.key,
					playlistInfo: request.data.val,
					overwriteVideos: true
				}
			})
			
			... The rest of the code.
```


`worker.js`:

```
// ---------- Firebase ----------

self.importScripts('/firebase/firebase-compat.js');

... The rest of the Firebase code

// ---------- Message Handlers ----------

self.addEventListener('message', e => {
    const data = e.data;
    switch (data.command) {
        case 'readDataOnce':
            readDataOnce(data.message).then(data =>
                self.postMessage({
                    command: 'readDataOnce',
                    message: data
                })
            )
            break;

        case 'updatePlaylistInfoInDB':
            updatePlaylistInfoInDB(
                data.message.playlistId,
                data.message.playlistInfo,
                data.message.overwriteVideos
            ).then(data =>
                self.postMessage({
                    command: 'updatePlaylistInfoInDB',
                    message: data
                })
            )
            break;

        case 'overwritePlaylistInfoInDB':
            updatePlaylistInfoInDB(
                data.message.playlistId,
                data.message.playlistInfo,
                data.message.overwriteVideos
            ).then(data =>
                self.postMessage({
                    command: 'overwritePlaylistInfoInDB',
                    message: data
                })
            )
            break;

        default:
            self.postMessage('Unknown command: ' + data.msg);
    };
}, false);

```

This code can be made less repetitive by creating helper functions for sending messages, but you get the gist.

But the problems don't end there. After hours of tinkering with the code, I still wasn't able to make it work in Firefox. I'm not experienced with making Chrome extensions, but I think you use Webpack or some other module bundler? Because some files are using code that is defined in other files and I don't see you using import and export statements.

But really, Firefox is insane for not supporting service workers for extensions. It makes porting Chrome extensions that use them tedious.

**Comment by TheAxlelotl** [comment] 2023-04-18 09:43
Also, here's some useful resources for working with web workers:

https://web.dev/workers-basics/#transferrable-objects
https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope
https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/importScripts

**Comment by NikkelM** [comment] 2023-04-18 11:16
Thanks for the updates. I'm travelling right now so will only be able to take a proper look at this later, but can already answer the question regarding the import/export statements:
If you take a look at the manifest.json, you'll see that in the content_scripts section I define multiple js files. This means that all of these files will be loaded sequentially in the 'context' of the extension. Therefore, all scripts can access all variables and functions of all the files that were imported before themselves, e.g. all files can access utils.js, but only content.js can access buildShuffleButton.js. If I remember correctly this is default behaviour for content scripts in chrome extensions, but maybe was only added with manifest v3.
I find it curious that apparently this functionality does not hold up when running the extension in Firefox, perhaps that has something to do with the webworkers as well.

**Comment by NikkelM** [comment] 2023-05-23 16:47
Hi @TheAxlelotl 
this is a bit of a late update, but while I've been working on the new features for v2.0.0 (which has now released), I've also been working on migrating the project to webpack - this basically allows for a smoother and more resilient workflow in the future.

One of the beneficial side effects of this migration is that many of the problems we were encountering before when porting the extension to Firefox have now been resolved. With my first tests, I was able to use the extension as expected with Firefox, with a slightly modified `manifest.json` to account for some of the differences between Chromium and Firefox. 

If you're still interested and would volunteer to test this "ported" beta version of the extension, I'd very much appreciate it. I'll attach a .zip of the extension below, which you should be able to extract and then add as a temporary extension on about:debugging#/runtime/this-firefox
I'll also take a closer look at what problems I might encounter when porting, but if you find any bugs do let me know!

[ryv-firefox-beta.zip](https://github.com/NikkelM/Random-YouTube-Video/files/11546585/ryv-firefox-beta.zip)

**Comment by TheAxlelotl** [comment] 2023-05-24 06:33
Hey @NikkelM 
So glad to hear an update from you. You've been working hard on this extension and I want you to know that all your hard work is appreciated.

I wanted to work more on the Firefox port, but I cannot find time to work on it because of my studies.

Interesting to see you migrate the project to Webpack. I do think that it will make the development of a cross-platform extension much easier. Not only would it solve the import/export issues, but you can also set Webpack to use the webextension-polyfill to handle the differences between Firefox and Chrome. 

I would gladly test the extension and tell you the details later. Excited to see how it works under the hood too.

Also, the new "Ignore shorts" feature is great. I wonder if there could be a feature in the future to randomly shuffle from your subscriptions (Eg. You click "Shuffle from Subscriptions" and it will randomly pick a YouTube channel from your subscriptions to shuffle to). That would probably require more permissions from the YouTube Data API though.

This extension's main draw is removing decision fatigue and analysis paralysis, so maybe it could randomize other aspects of YouTube that involve decision-making to make it the best extension for just relaxing with YouTube videos after a hard day's work.

Anyways, I really wish this extension can garner more traction and I wish you success. I'll give you an update about `ryv-firefox-beta` soon.

**Comment by NikkelM** [comment] 2023-05-24 08:55
Thanks for the suggestions, I'll take note of them. As you said, especially an option that needs access to your subscriptions would need elevated access with the YouTube API, so it might be a bit more extensive when implementing.
If you have other ideas on what you'd like to have randomized on YouTube, feel free to always open an issue and I'll take a look.

**Comment by TheAxlelotl** [comment] 2023-05-28 03:35
@NikkelM Time for a report.

I have tested the extension on Firefox (I am using the developer edition). I installed it temporarily 
using `about:debugging`, and I've also installed it permanently by making a build version using `web-ext build`. 

I have been using the extension every night after my studies for the past 3 days, and I tested every feature of the extension including passing my API key, and I haven't seen any bugs. 

Except for a minor UI issue. When you `Shuffle from the most recent % of videos`, the box where you put the percentage is too small and can only show up to 1 digit. I even thought that you can only put up to 9% because of it. The Chrome version doesn't seem to have the issue.

Other than that, the extension is working flawlessly and is as awesome as ever.

**Comment by NikkelM** [comment] 2023-05-28 12:41
Thanks for the info. I'm working on setting up a build/release pipeline to support Firefox releases as well right now, and am working on fixing a few bugs I found in the backend.
Regarding the popup UI bug: This is due to vendor specific CSS attributes, where the arrows for the input fields are incorrectly still being displayed due to missing attributes. That should be a quick fix

**Comment by NikkelM** [comment] 2023-05-28 14:10
I've now opened #184 related to this. I'll do some more testing over the next few days before releasing this, but if you want to continue testing the new version, you can bundle the new files using `npm run build:firefox` after cloning the branch and installing the dependencies. The issues you noted should already have been resolved.

**Closed** 2023-06-02 13:35 UTC
Labels: Feature, Priority: Unimportant, UX

**Comment by NikkelM** [comment] 2023-06-02 14:12
I've just submitted the Firefox version for review in the Mozilla Add-On store. After it's been released, you can find it [here](https://addons.mozilla.org/en-GB/firefox/addon/random-youtube-video/).

**Comment by TheAxlelotl** [comment] 2023-06-04 04:52
Great job on the port! Really grateful to you for immediately working on it when I asked about it. I will try to contribute to the extension when I have the time. I'm quite busy with my studies though. I'll make a donation when I can and will try to spread the word about the extension.
